### ISSUE TITLE
友链变更

### ISSUE THREAD

**Issue by jackyfzh** [Eliot00/elliot00.com#39]
Hello公子政，您博客[这个页面](https://elliot00.com/about)的友链[Jacky的个人博客](https://jackypy.xyz)现已无法访问，链接变更为[这个](https://jackyfzh.github.io)。本站已添加贵站友链，望更改，谢谢。

**Comment by Eliot00** [comment]
@jackyfzh 已变更

**Comment by jackyfzh** [comment]
谢谢
